{% set name = "wagtail-bakery" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtail-bakery-{{ version }}.tar.gz
  sha256: 6ed7bfca032ef69daa51267ea820d4a9780620783559122684f92569c1467ebc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django-bakery >=0.13.1,<0.14.0
    - wagtail >=4.1

test:
  imports:
    - wagtailbakery
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wagtail-nest/wagtail-bakery/
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A set of helpers for baking your Django Wagtail site out as flat files'
  description: |
    Wagtail-bakery is built on top of Django bakery. Wagtail-bakery is not limited to 
    build Wagtail pages specifically, mixed content is possible!
  doc_url: hhttps://wagtail-bakery.readthedocs.io
  dev_url: https://github.com/wagtail-nest/wagtail-bakery/

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
    - sannykr
