travis:
  secure:
    BINSTAR_TOKEN: voLZ8tXxO5hpEUR+BDPN0HTqnbI4SDAAsc3NoURmo/xJ0JE+d21R2AzJ+vwLAfuw752kzL/XjQzZGqutPNCTSoyNX9A0svTwalzs/SDwoGgL6tBNbm2hHajofJNVzDMyquW7UWGyQRwngE52KcxVZMiGSdVFekpTHWS442kS6hxgQ/81yhb7V7gE43YixGQD7/OrdAtgcZgGPlu5Ls39FKeADvNgwEqfwEzCeP1zQ9fz8QowtAgdabE/Ay3BvQbeKeQDZ/De08EU0OYoc94keX/DQ4hbYaNt9rB8AYQDJZwf5eLjL2ewi3DG9EeSJN2X4RiTnVIyZ3euir6P8Acd/mlp99TYjZ9Z3KpRY24lfen53gx3u4tmVPnAT756/UmrtIFbbITVxPfLogLcApUxDMN9xR+Iu93ktVfCd6Su7Jw+O8q+2M+p9Z5uD5o0EL5tBv904rUqtm9g6WdVOQXDeGyfmiuMw/QJWjeECrbOYyLZK5ic9u3VBIhGHT+aIt4jeePkFv+A3efGEInkBYoHj1+FFbn5/eLu0GGLeDNTmr+bqRmHblsADyS7FGLJOwAwsB3fSyDyo2gow3EZjQlR6HfOSxwc5o/xE4sWj4vmcAMRsI78rG3n4mW5GA4KrQqyC8WP+6wVmiTusISigyGa2a7dstNQNz1j6frp+nC33JU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
