travis:
  secure:
    BINSTAR_TOKEN: AerihmYD2o0pJhgaHRckDqTrXqmsyMGVzE+mBEG2j1qxjZ6J7RuTjuqxhpaedB0Iz7MTH0MzrEENjdrrsRVQrrDYdIu7C3Pv4PYWTcvLXFpnJrpA+8h42yC80/u9n8jYQwuksiKj3G3JpwPuvCB0t3hUQpakCjMgr6uUAiFAIzoPzzYDNjSF+LahGnXtA3ywgzzb7ZWqGExa6EOkAmmzF1q2WRhchZhon+mODtPRCdjJedUtxKrOggczXL5bvgN+ZU6Q2ysBGY2zTLnkfXAwM+itf5NpeOQZchYIVwyhatBMlgNUlPlBJLsN7J8hDr8FvvkfDNMLE6AOFuhLNbf5nx5utGBf01NFuWyUlrpQvDNLNBQgMnPuTxeQMkvACLDmRSp7UfljvgsZV/Q5KlVAmlvBfndQHpSese+LfLGRXpHzSlJEr//KW+0JG7GyrMl6f3VTJTBV1rJxY2SFsRwcfh1TkHm1g4rHsWGUYrf/8L4HRb9uxAIOeLNqMQ6SEXAfgKLdHaB/+Ap4NmcADKfYwQG2zFnJsqEEcycEvCXjgtdrVzpvS+nZLeH71ku4TnLGYX6VaQ2uWot9ouUh+YTBwaSDtS766fe8sev8kf5KB3pWu+kVYOdoBS5vHor8wSZhE60PVGh9zMb2w8wcjfIF8z13b7ZMS+Xm2H2P4Rp3bzM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
